name: api_provider
description:
# version: 0.0.1
homepage: https://tapped.dev
author: Tapped <contact@tapped.dev>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  codable:
    git:
      url: git://github.com/tappeddev/codable.git

dev_dependencies:
  extra_pedantic: 1.1.1
  pedantic: ^1.8.0+1
  test: ^1.6.0
