name: api_provider
description:
# version: 0.0.1
# homepage: https://tikkr.app
# author: julianbissekkou <julianbissekkou@hotmail.de>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  codable:
    git:
      url: git://github.com/tikkrapp/codable.git
  dio: ^3.0.3

dev_dependencies:
  pedantic: ^1.8.0+1
  test: ^1.6.0
